In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('D:/mariam main/GUC/project/final project/Nike_Sales_Uncleaned.csv')

In [3]:
df.head(20)

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.00,3/9/2024,Online,bengaluru,-770.45
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,NaN,0.00,7/9/2024,Retail,Hyd,-112.53
2,2002,Women,Soccer,Premier III,M,4.0,NaN,NaN,0.00,NaN,Retail,Mumbai,3337.34
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,NaN,0.00,4/10/2024,Online,Pune,3376.85
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,NaN,0.00,9/12/2024,Retail,Delhi,187.89
5,2005,Women,Training,Flex Trainer,M,1.0,7363.96,NaN,0.00,NaN,Retail,Delhi,1415.98
6,2006,Men,Training,SuperRep Go,M,NaN,6819.78,NaN,0.00,4/6/2025,Online,Bangalore,1802.09
7,2007,Kids,Training,SuperRep Go,M,1.0,NaN,0.32,0.00,NaN,Retail,Bangalore,2928.36
8,2008,Women,Soccer,Premier III,11,-1.0,NaN,NaN,0.00,11/10/2024,Online,Hyderabad,-731.18
9,2009,Men,Soccer,Mercurial Superfly,M,4.0,NaN,NaN,0.00,NaN,Online,Pune,3929.61
10,2010,Kids,Lifestyle,Waffle One,L,1.0,7949.83,NaN,0.00,1/16/2025,Online,Pune,1965.56
11,2011,Women,Training,Flex Trainer,L,-1.0,9586.08,NaN,0.00,NaN,Retail,Hyd,1667.08
12,2018,Kids,Lifestyle,Blazer Mid,NaN,-1.0,NaN,0.86,0.00,13-11-2024,Online,Delhi,2109.48
13,2013,Kids,Training,SuperRep Go,NaN,NaN,9671.05,NaN,0.00,19-09-2024,Online,hyderbad,299.34
14,2014,Women,Running,React Infinity,11,NaN,NaN,NaN,0.00,4/12/2025,Online,Bangalore,-1044.40
15,2015,Kids,Basketball,Air Jordan,NaN,NaN,3285.52,NaN,0.00,31-05-2025,Retail,Kolkata,1193.21
16,2016,Women,Basketball,Air Jordan,M,1.0,9871.75,0.30,6910.22,NaN,Retail,hyderbad,2452.69
17,2017,Women,Basketball,Air Jordan,9,4.0,NaN,NaN,0.00,17-03-2025,Retail,Delhi,1946.24
18,2018,Men,Training,Metcon 7,XL,0.0,NaN,1.17,0.00,NaN,Online,bengaluru,-966.89
19,2019,Kids,Running,Air Zoom,6,0.0,3424.06,0.32,0.00,1/17/2025,Online,Hyderabad,1915.24

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Size              1990 non-null   object
 5   Units_Sold        1265 non-null   float64
 6   MRP               1246 non-null   float64
 7   Discount_Applied  832 non-null    float64
 8   Revenue           2500 non-null   float64
 9   Order_Date        1884 non-null   object
 10  Sales_Channel     2500 non-null   object
 11  Region            2500 non-null   object
 12  Profit            2500 non-null   float64
dtypes: float64(5), int64(1), object(7)
memory usage: 254.0+ KB

size completed

In [5]:
clothing_sizes = ['M', 'L', 'XL']
df['clothing_sizes'] =df['Size'].apply(lambda x: x if x in clothing_sizes else None)
df['Shoe_Size'] = df['Size'].apply(lambda x: x if x not in clothing_sizes else None)

region completeted

In [6]:
region_mapping = {
    'bengaluru': 'Bangalore',
    'hyderbad': 'Hyderabad',
    'Hyd': 'Hyderabad'
}

df['Region']=df['Region'].replace(region_mapping)
df.drop(columns=['Size'], inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Units_Sold        1265 non-null   float64
 5   MRP               1246 non-null   float64
 6   Discount_Applied  832 non-null    float64
 7   Revenue           2500 non-null   float64
 8   Order_Date        1884 non-null   object
 9   Sales_Channel     2500 non-null   object
 10  Region            2500 non-null   object
 11  Profit            2500 non-null   float64
 12  clothing_sizes    1503 non-null   object
 13  Shoe_Size         487 non-null    object
dtypes: float64(5), int64(1), object(8)
memory usage: 273.6+ KB

date completed

In [8]:


# Safer parsing that automatically detects and converts mixed date structures instead of breaking them
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', errors='ignore').dt.strftime('%Y/%m/%d')

cheack absoulute values

In [9]:
# df['Revenue'] = df['Revenue'].abs()
df['Units_Sold'] = df['Units_Sold'].abs()
# df['Discount_Applied']=df['Discount_Applied'].abs()
# df['Order_Date'] = df['Order_Date'].fillna('-')

df

,Order_ID,Gender_Category,Product_Line,Product_Name,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit,clothing_sizes,Shoe_Size
0,2000,Kids,Training,SuperRep Go,NaN,NaN,0.47,0.0,2024/03/09,Online,Bangalore,-770.45,M,None
1,2001,Women,Soccer,Tiempo Legend,3.0,4957.93,NaN,0.0,2024/07/09,Retail,Hyderabad,-112.53,M,None
2,2002,Women,Soccer,Premier III,4.0,NaN,NaN,0.0,NaN,Retail,Mumbai,3337.34,M,None
3,2003,Kids,Lifestyle,Blazer Mid,NaN,9673.57,NaN,0.0,2024/04/10,Online,Pune,3376.85,L,None
4,2004,Kids,Running,React Infinity,NaN,NaN,NaN,0.0,2024/09/12,Retail,Delhi,187.89,XL,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,4495,Kids,Basketball,Kyrie Flytrap,3.0,NaN,NaN,0.0,2025/05/14,Online,Pune,2.97,XL,None
2496,4496,Men,Basketball,Kyrie Flytrap,1.0,NaN,NaN,0.0,NaN,Online,Hyderabad,-487.36,L,None
2497,4497,Men,Soccer,Tiempo Legend,NaN,6647.60,0.52,0.0,2025/02/07,Retail,Bangalore,-918.14,None,7
2498,4498,Women,Training,ZoomX Invincible,4.0,5358.70,NaN,0.0,2024/11/12,Online,Mumbai,3352.29,None,NaN
2499,4499,Women,Running,Air Zoom,NaN,5550.99,NaN,0.0,2024/11/23,Retail,Mumbai,2453.57,M,None

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Units_Sold        1265 non-null   float64
 5   MRP               1246 non-null   float64
 6   Discount_Applied  832 non-null    float64
 7   Revenue           2500 non-null   float64
 8   Order_Date        1884 non-null   object
 9   Sales_Channel     2500 non-null   object
 10  Region            2500 non-null   object
 11  Profit            2500 non-null   float64
 12  clothing_sizes    1503 non-null   object
 13  Shoe_Size         487 non-null    object
dtypes: float64(5), int64(1), object(8)
memory usage: 273.6+ KB

revenu

In [11]:
df.head(10)

,Order_ID,Gender_Category,Product_Line,Product_Name,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit,clothing_sizes,Shoe_Size
0,2000,Kids,Training,SuperRep Go,NaN,NaN,0.47,0.0,2024/03/09,Online,Bangalore,-770.45,M,None
1,2001,Women,Soccer,Tiempo Legend,3.0,4957.93,NaN,0.0,2024/07/09,Retail,Hyderabad,-112.53,M,None
2,2002,Women,Soccer,Premier III,4.0,NaN,NaN,0.0,NaN,Retail,Mumbai,3337.34,M,None
3,2003,Kids,Lifestyle,Blazer Mid,NaN,9673.57,NaN,0.0,2024/04/10,Online,Pune,3376.85,L,None
4,2004,Kids,Running,React Infinity,NaN,NaN,NaN,0.0,2024/09/12,Retail,Delhi,187.89,XL,None
5,2005,Women,Training,Flex Trainer,1.0,7363.96,NaN,0.0,NaN,Retail,Delhi,1415.98,M,None
6,2006,Men,Training,SuperRep Go,NaN,6819.78,NaN,0.0,2025/04/06,Online,Bangalore,1802.09,M,None
7,2007,Kids,Training,SuperRep Go,1.0,NaN,0.32,0.0,NaN,Retail,Bangalore,2928.36,M,None
8,2008,Women,Soccer,Premier III,1.0,NaN,NaN,0.0,2024/11/10,Online,Hyderabad,-731.18,None,11
9,2009,Men,Soccer,Mercurial Superfly,4.0,NaN,NaN,0.0,NaN,Online,Pune,3929.61,M,None

In [12]:



# Step 1: Fix the MRP column first by copying prices from matching duplicate rows
mrp_by_group = df.groupby(['Product_Name', 'Product_Line', 'Gender_Category'])['MRP'].transform('first')
df['MRP'] = df['MRP'].fillna(mrp_by_group)

# Handle any global fallback for prices just in case
df['MRP'] = df['MRP'].fillna(df['MRP'].median())

# Clean up discounts safely (fill missing discounts with 0.0)
discount_clean = df['Discount_Applied'].fillna(0.0).clip(0.0, 1.0)

# Step 2: Implement your two conditional rules row-by-row
def fix_math_rows(row, discount_series):
    units = row['Units_Sold']
    mrp = row['MRP']
    rev = row['Revenue']
    disc = discount_series[row.name]
    
    # Rule 2: If Revenue is already written, back-calculate missing Units_Sold
    if pd.notna(rev) and rev > 0 and pd.isna(units):
        calculated_units = rev / (mrp * (1 - disc))
        units = round(calculated_units)
    elif rev == 0 and pd.isna(units):
        units = 0.0
        
    # Rule 1: If Units and MRP exist, calculate/re-verify the Revenue
    if pd.notna(units) and pd.notna(mrp):
        rev = units * mrp * (1 - disc)
        
    return pd.Series([units, round(rev, 2)])

# Apply the rules directly to update your dataframe columns cleanly
df[['Units_Sold', 'Revenue']] = df.apply(lambda r: fix_math_rows(r, discount_clean), axis=1)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Units_Sold        2500 non-null   float64
 5   MRP               2500 non-null   float64
 6   Discount_Applied  832 non-null    float64
 7   Revenue           2500 non-null   float64
 8   Order_Date        1884 non-null   object
 9   Sales_Channel     2500 non-null   object
 10  Region            2500 non-null   object
 11  Profit            2500 non-null   float64
 12  clothing_sizes    1503 non-null   object
 13  Shoe_Size         487 non-null    object
dtypes: float64(5), int64(1), object(8)
memory usage: 273.6+ KB

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Units_Sold        2500 non-null   float64
 5   MRP               2500 non-null   float64
 6   Discount_Applied  832 non-null    float64
 7   Revenue           2500 non-null   float64
 8   Order_Date        1884 non-null   object
 9   Sales_Channel     2500 non-null   object
 10  Region            2500 non-null   object
 11  Profit            2500 non-null   float64
 12  clothing_sizes    1503 non-null   object
 13  Shoe_Size         487 non-null    object
dtypes: float64(5), int64(1), object(8)
memory usage: 273.6+ KB

In [15]:
# 1. Group by the matching categories and get the actual written price from duplicate rows
duplicate_prices = df.groupby(['Product_Name', 'Product_Line', 'Gender_Category'])['MRP'].transform('first')

# 2. Overwrite the missing gaps in the original column
df['MRP'] = df['MRP'].fillna(duplicate_prices)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Units_Sold        2500 non-null   float64
 5   MRP               2500 non-null   float64
 6   Discount_Applied  832 non-null    float64
 7   Revenue           2500 non-null   float64
 8   Order_Date        1884 non-null   object
 9   Sales_Channel     2500 non-null   object
 10  Region            2500 non-null   object
 11  Profit            2500 non-null   float64
 12  clothing_sizes    1503 non-null   object
 13  Shoe_Size         487 non-null    object
dtypes: float64(5), int64(1), object(8)
memory usage: 273.6+ KB

In [17]:
df.head(20)

,Order_ID,Gender_Category,Product_Line,Product_Name,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit,clothing_sizes,Shoe_Size
0,2000,Kids,Training,SuperRep Go,0.0,9671.05,0.47,0.00,2024/03/09,Online,Bangalore,-770.45,M,None
1,2001,Women,Soccer,Tiempo Legend,3.0,4957.93,NaN,14873.79,2024/07/09,Retail,Hyderabad,-112.53,M,None
2,2002,Women,Soccer,Premier III,4.0,5172.14,NaN,20688.56,NaN,Retail,Mumbai,3337.34,M,None
3,2003,Kids,Lifestyle,Blazer Mid,0.0,9673.57,NaN,0.00,2024/04/10,Online,Pune,3376.85,L,None
4,2004,Kids,Running,React Infinity,0.0,7557.71,NaN,0.00,2024/09/12,Retail,Delhi,187.89,XL,None
5,2005,Women,Training,Flex Trainer,1.0,7363.96,NaN,7363.96,NaN,Retail,Delhi,1415.98,M,None
6,2006,Men,Training,SuperRep Go,0.0,6819.78,NaN,0.00,2025/04/06,Online,Bangalore,1802.09,M,None
7,2007,Kids,Training,SuperRep Go,1.0,9671.05,0.32,6576.31,NaN,Retail,Bangalore,2928.36,M,None
8,2008,Women,Soccer,Premier III,1.0,5172.14,NaN,5172.14,2024/11/10,Online,Hyderabad,-731.18,None,11
9,2009,Men,Soccer,Mercurial Superfly,4.0,6196.01,NaN,24784.04,NaN,Online,Pune,3929.61,M,None
10,2010,Kids,Lifestyle,Waffle One,1.0,7949.83,NaN,7949.83,2025/01/16,Online,Pune,1965.56,L,None
11,2011,Women,Training,Flex Trainer,1.0,9586.08,NaN,9586.08,NaN,Retail,Hyderabad,1667.08,L,None
12,2018,Kids,Lifestyle,Blazer Mid,1.0,9673.57,0.86,1354.30,2024/11/13,Online,Delhi,2109.48,None,NaN
13,2013,Kids,Training,SuperRep Go,0.0,9671.05,NaN,0.00,2024/09/19,Online,Hyderabad,299.34,None,NaN
14,2014,Women,Running,React Infinity,0.0,8136.39,NaN,0.00,2025/04/12,Online,Bangalore,-1044.40,None,11
15,2015,Kids,Basketball,Air Jordan,0.0,3285.52,NaN,0.00,2025/05/31,Retail,Kolkata,1193.21,None,NaN
16,2016,Women,Basketball,Air Jordan,1.0,9871.75,0.30,6910.22,NaN,Retail,Hyderabad,2452.69,M,None
17,2017,Women,Basketball,Air Jordan,4.0,9871.75,NaN,39487.00,2025/03/17,Retail,Delhi,1946.24,None,9
18,2018,Men,Training,Metcon 7,0.0,4020.50,1.17,0.00,NaN,Online,Bangalore,-966.89,XL,None
19,2019,Kids,Running,Air Zoom,0.0,3424.06,0.32,0.00,2025/01/17,Online,Hyderabad,1915.24,None,6

In [18]:
# Filter for rows where Profit is less than 0, then group by Sales_Channel
negative_profit_counts = df[df['Profit'] < 0].groupby('Sales_Channel').size()

print("Number of negative Profit records by Sales Channel:")
print(negative_profit_counts)

Number of negative Profit records by Sales Channel:
Sales_Channel
Online    296
Retail    282
dtype: int64

In [19]:
df['Discount_Applied']=df['Discount_Applied'].fillna(0).clip(upper =  0.99)

In [20]:
df['Profit']= df['Profit'].abs()
def apply_accurate_reverse_engineering(row):
    units = row['Units_Sold']
    rev = row['Revenue']
    mrp = row['MRP']
    profit = row['Profit']
    disc = row['Discount_Applied']
    
    is_rev_zero = pd.isna(rev) or rev == 0.0
    is_units_zero = pd.isna(units) or units == 0.0
    
    if is_rev_zero and is_units_zero:
        if pd.notna(profit) and profit != 0:
            # 1. Estimate base value from profit margin
            estimated_discounted_value = abs(profit) / 0.35
            
            # 2. Find the true price of one shoe after discount
            discounted_price_per_unit = mrp * (1 - disc)
            
            # 3. Solve for units cleanly (e.g., 2201.29 / 5125.66 = ~0.43 -> rounded to 1 unit)
            if discounted_price_per_unit > 0:
                units = max(1, round(estimated_discounted_value / discounted_price_per_unit))
            else:
                units = 1
            
            # 4. Final Revenue matches the physical unit sale!
            rev = round(units * mrp * (1 - disc), 2)
        else:
            rev = 0.0
            units = 0
            
    return pd.Series([int(units), rev])

# Overwrite only the target rows
df[['Units_Sold', 'Revenue']] = df.apply(apply_accurate_reverse_engineering, axis=1)

In [21]:
df.head(30)

,Order_ID,Gender_Category,Product_Line,Product_Name,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit,clothing_sizes,Shoe_Size
0,2000,Kids,Training,SuperRep Go,1.0,9671.05,0.47,5125.66,2024/03/09,Online,Bangalore,770.45,M,None
1,2001,Women,Soccer,Tiempo Legend,3.0,4957.93,0.00,14873.79,2024/07/09,Retail,Hyderabad,112.53,M,None
2,2002,Women,Soccer,Premier III,4.0,5172.14,0.00,20688.56,NaN,Retail,Mumbai,3337.34,M,None
3,2003,Kids,Lifestyle,Blazer Mid,1.0,9673.57,0.00,9673.57,2024/04/10,Online,Pune,3376.85,L,None
4,2004,Kids,Running,React Infinity,1.0,7557.71,0.00,7557.71,2024/09/12,Retail,Delhi,187.89,XL,None
5,2005,Women,Training,Flex Trainer,1.0,7363.96,0.00,7363.96,NaN,Retail,Delhi,1415.98,M,None
6,2006,Men,Training,SuperRep Go,1.0,6819.78,0.00,6819.78,2025/04/06,Online,Bangalore,1802.09,M,None
7,2007,Kids,Training,SuperRep Go,1.0,9671.05,0.32,6576.31,NaN,Retail,Bangalore,2928.36,M,None
8,2008,Women,Soccer,Premier III,1.0,5172.14,0.00,5172.14,2024/11/10,Online,Hyderabad,731.18,None,11
9,2009,Men,Soccer,Mercurial Superfly,4.0,6196.01,0.00,24784.04,NaN,Online,Pune,3929.61,M,None
10,2010,Kids,Lifestyle,Waffle One,1.0,7949.83,0.00,7949.83,2025/01/16,Online,Pune,1965.56,L,None
11,2011,Women,Training,Flex Trainer,1.0,9586.08,0.00,9586.08,NaN,Retail,Hyderabad,1667.08,L,None
12,2018,Kids,Lifestyle,Blazer Mid,1.0,9673.57,0.86,1354.30,2024/11/13,Online,Delhi,2109.48,None,NaN
13,2013,Kids,Training,SuperRep Go,1.0,9671.05,0.00,9671.05,2024/09/19,Online,Hyderabad,299.34,None,NaN
14,2014,Women,Running,React Infinity,1.0,8136.39,0.00,8136.39,2025/04/12,Online,Bangalore,1044.40,None,11
15,2015,Kids,Basketball,Air Jordan,1.0,3285.52,0.00,3285.52,2025/05/31,Retail,Kolkata,1193.21,None,NaN
16,2016,Women,Basketball,Air Jordan,1.0,9871.75,0.30,6910.22,NaN,Retail,Hyderabad,2452.69,M,None
17,2017,Women,Basketball,Air Jordan,4.0,9871.75,0.00,39487.00,2025/03/17,Retail,Delhi,1946.24,None,9
18,2018,Men,Training,Metcon 7,69.0,4020.50,0.99,2774.15,NaN,Online,Bangalore,966.89,XL,None
19,2019,Kids,Running,Air Zoom,2.0,3424.06,0.32,4656.72,2025/01/17,Online,Hyderabad,1915.24,None,6
20,2020,Kids,Soccer,Tiempo Legend,1.0,5553.88,0.67,1832.78,2025/03/28,Retail,Mumbai,439.96,L,None
21,2021,Men,Running,Free RN,1.0,7086.70,0.66,2409.48,2024/11/19,Retail,Hyderabad,1120.49,L,None
22,2022,Women,Soccer,Premier III,2.0,5172.14,0.00,10344.28,2024/09/24,Online,Pune,3427.16,M,None
23,2023,Men,Lifestyle,Waffle One,1.0,5003.95,0.00,5003.95,2025/10/01,Online,Mumbai,1498.37,M,None
24,2024,Kids,Training,SuperRep Go,1.0,9671.05,0.50,4835.52,2024/12/28,Retail,Bangalore,1842.35,XL,None
25,2025,Women,Basketball,Kyrie Flytrap,3.0,9820.50,0.00,29461.50,NaN,Retail,Mumbai,1900.15,M,None
26,2026,Kids,Lifestyle,Blazer Mid,1.0,9673.57,0.16,8125.80,2024/08/10,Retail,Kolkata,2301.64,XL,None
27,2027,Men,Basketball,Zoom Freak,1.0,9106.61,0.22,7103.16,NaN,Online,Pune,138.74,XL,None
28,2028,Men,Training,Flex Trainer,1.0,3270.23,0.00,3270.23,NaN,Retail,Delhi,946.86,None,12
29,2029,Men,Training,ZoomX Invincible,1.0,5690.69,0.00,5690.69,2023/10/28,Online,Bangalore,185.67,None,12

In [22]:
# 4. Save the dataset with only the corrected Revenue
df.to_csv('Nike_Sales_Cleaned.csv', index=False)
print("Finished! Only the Revenue column has been updated.")

Finished! Only the Revenue column has been updated.